### ISSUE TITLE
Is this a fork?

### ISSUE THREAD

**Issue by anderspitman** [kirsle/configdir#1]
of https://github.com/shibukawa/configdir

**Comment by kirsle** [comment]
Hey, no this isn't a fork of that module but an independent project. That module seems to have additional functionality over my version.

I didn't see that one when I started mine; one module that I _did_ find back then (I forgot the name of it) was opinionated and did too much stuff (duplicated `os` functionality to mkdir, create/open file, etc.) when all I wanted was a no-nonsense lookup of the directory paths and I can do that extra stuff in my own app, so I wrote my configdir module.

**Comment by anderspitman** [comment]
Cooleo. It just looked really similar at first glance. Thanks for the project. I ended up rolling my own so I could have it in a single file, but copying your code helped me get going a lot faster :+1:
